### ISSUE TITLE
Inkscape 1.0

### ISSUE THREAD

**Issue by santos89ers** [butesa/ink-generator-python#4]
is there any attempt to upgrade the extension to be use with Inkscape 1.0? try the extension with Inkscape 1.0rc1, it's throw an exception 
==========================
Traceback (most recent call last):
  File "generator.py", line 362, in <module>
    Process_csv_file(csvfile)
  File "generator.py", line 304, in Process_csv_file
    csvdata = [row.items() for row in csv.DictReader(csvfile)]
  File "generator.py", line 304, in <listcomp>
    csvdata = [row.items() for row in csv.DictReader(csvfile)]
  File "C:\Users\DinkesKeu\Downloads\Compressed\inkscape-1.0rc1-x64\inkscape\lib\python3.8\csv.py", line 110, in __next__
    self.fieldnames
  File "C:\Users\DinkesKeu\Downloads\Compressed\inkscape-1.0rc1-x64\inkscape\lib\python3.8\csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
=======================================

**Comment by butesa** [comment]
I have not tried Inkscape 1.0 yet.
But yes, I'd like to have this Plugin compatible to 1.0.

**Comment by santos89ers** [comment]
I'm glad to hear that. Your awesome extension is a truly time saver, thank you. 

Best regards

**Comment by VB-52** [comment]
Hi, Inkscape 1.0 uses python 3, most necessary changes are related to this and the fact that Python 3 defaults to UTF-8 . I adapted the generator for my use to work with the new Inkscape. I have not fully tested it but feel free to start from my version for your new release. You can find it in my forked repository.

**Comment by santos89ers** [comment]
Hi, VB-52, glad to hear that, I'd like to test it, and inform as soon as possible

**Comment by santos89ers** [comment]
Hi VB-52, tested on my Windows 10 x64 machine, using Inkscape 1.0 portable (no install). It works like a charm, awesome.

Minor issue I have found so far:
1. Rather slow than in 0.92 vers, but that may caused by my lack of PC resources. (Pentium G3220, 4GB RAM)
2. Dialog box just show letter "Y" when the extension of filename specified in output box not match with in the combobox. Pressing yes or no still work like the 0.92 vers though.
3. JPG export, have no ImageMagick installed, so I cannot test it yet.

Thanks again, you are all amazing guys.

**Comment by butesa** [comment]
Hello,

I updated the code (based on the work of @VB-52).
I have tested it on Windows 64 bit with Inkscape 0.92.4 and Inkscape 1.0 and on Linux with 0.91.

**Comment by sg000** [comment]
So I just tossed the May 21 version (ink-generator-python-1.0) by @butesa (btw, awesome, very useful) and when I run I get a nearly blank window with a "Y" with a Yes/No confirm, then if I hit yes or no, an error message like above. 
EDIT: I am doing a PNG output, so not the JPEG that has issues.
Windows 10, 64-bit, brand new Inkscape 1.0 (May 1 release) install, only version that's been on this computer. 
Did I miss something in the install?

**Comment by VB-52** [comment]
Hi, 

thank you for updating and sorry for the delay. I finally came around to test the new version when generating a new calendar. I did not have any issues with the plugin with python 3.9.1 and inkscape 1.0.1 in Linux. I tested your example with all image types. also one of my scripts on the console with pdf and in the gui with all image formats. I only found some minor issues, that have probably been there before: 
1. If jpeg is selected as export format, (background) transparency values of 0 (i.e. inkscape canvas) leads to black background with jagged colored artefacts along transparency borders (see attachments). If I add "-alpha remove" to imagemagick options (e.g. manually converted with: convert Ada\ Lovelace.png -alpha remove Ada\ Lovelace_cv.jpg), background is white and edges are smooth as in other export formats. 
2. if eps is selected as export format, objects outside of the page area are included in the export area. I guess one of inkscape's export-area options would help here, but did not test any further.

jpg images:
a) straight from script:
![Ada Lovelace](https://user-images.githubusercontent.com/65509943/103240993-388f6680-4952-11eb-98ee-3db3932bbe20.jpg)

b) from png with alpha remove:
![Ada Lovelace_cv](https://user-images.githubusercontent.com/65509943/103241036-52c94480-4952-11eb-85a2-1e7b661a4a3d.jpg)
